### ISSUE TITLE
`extract-text-webpack-plugin` depreciation in Webpack 4

### ISSUE THREAD

**Issue by caongocthai** [esausilva/react-starter-boilerplate-hmr#3]
Hi Esau. You've done a great job on your article about configuring Webpack for React. Thank you for teaching me a lot through that.

One problem though is that [Webpack doesn't recommend using](https://github.com/webpack-contrib/extract-text-webpack-plugin#usage) `extract-text-webpack-plugin` for Webpack anymore, but `mini-css-extract-plugin` instead.

Are you planning to update the repo as well as the article to include this?

**Comment by esausilva** [comment]
Hi Harry, you are welcome. Thanks for the comment.

Regarding `extract-text-webpack-plugin`, I am aware that they recommend to use `mini-css-extract-plugin` instead. The only reason I am not using it is because `mini-css-extract-plugin ` does not support `style-loader` (https://github.com/webpack-contrib/mini-css-extract-plugin#advanced-configuration-example) and when creating the production build, I have to manually add the outputted CSS file to my `index.html`.

I have not found a way to accomplish this automatically, if you know of a way let me know 🙂

But I guess I can put a note in my tutorial about it
